### ISSUE TITLE
 It can't convert QSharedPointer successfully.

### ISSUE THREAD

**Issue by ghost** [marcel-goldschen-ohm/QtPropertySerializer#3]

**Comment by marcel-goldschen-ohm** [comment]
Yes, currently it only handles property values or QObject pointers. Certainly, one could grab the value referenced by a QSharedPointer and serialize that. However, serialization typically goes hand in hand with deserialization, and it is not clear to me how you would deserialize such an object. If you have some cases where this would actually be useful, please let me know.

**Comment by marcel-goldschen-ohm** [comment]
To implement something that can handle arbitrary references would likely require a different data structure than a simple tree as is currently used. I think we'd need a more complicated graph structure to handle potentially arbitrary linkage between nodes for references. Certainly this is possible, but probably would require a total rewrite of the current simple tree based serialization.
